### ISSUE TITLE
Not working with opencv current versions 

### ISSUE THREAD

**Issue by ManojDjs** [giladoved/webcam-heart-rate-monitor#1]
Can you please update with current opencv version

**Comment by giladoved** [comment]
This project is not active, but I'll accept a PR

**Comment by matkaan** [comment]
Tested with latest python and opencv. Worked nicely with few changes. Thanks for the nice little project.

Replace:
1.  "cv2.cv.CV_FOURCC" -> "cv2.VideoWriter_fourcc" (lines 44, 48)
2. "videoHeight/2" -> "videoHeight//2" AND"videoWidth/2" -> "videoWidth//2" (lines 94, 124, 125).

**Comment by MarkusvonStaden** [comment]
I created a PR with the fix.

**Comment by giladoved** [comment]
Thanks for the PR. Issue is fixed with https://github.com/giladoved/webcam-heart-rate-monitor/pull/2
